elastic/synthetics-recorder

nodemon.json, package.json
Today when we make changes to our `electron` code, we need to restart the process to see them reflected. This can be frustrating when debugging or adding new functionality.
These changes introduce `nodemon` to manage the restart for us manually when we're targeting the electron files. It shouldn't need to watch anything else since react scripts will automatically reload the frontend files for us.
=> chore: Add `nodemon`

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/other.yml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
This PR closes https://github.com/elastic/synthetics-recorder/issues/109 by adding the missing repo-level documentation, including:
* A small contribution guide
* Issue templates
* A pull-request template
I tried to follow a pattern similar to most open-source repos to which I contribute, and tried to use patterns which make the repo approachable for external contributors too. I've also had a look at other Elastic repos to be sure the contents here would be okay.
**NOTE**: You can validate these issue templates [here](https://github.com/lucasfcosta/synthetics-recorder/blob/repo-docs/.github/ISSUE_TEMPLATE).
=> Add repo-level documentation

.ci/Jenkinsfile, .npmrc, package-lock.json
This PR changes the command we use to install dependencies on CI from `npm install` to `npm ci`.
When using `npm install` you get the newest "non-breaking" versions of packages (according to the authors which versioned it). That means you may get packages with changes that cause the build to behave differently, and that could even cause the build to fail, as one cannot rely on third parties to follow `semver` strictly.
The `npm ci` command, on the other hand, uses the `package-lock.json` file to get the exact same dependencies that you had in your machine, down to the patch version. That ensures our builds will be repeatable.
It also makes the build slightly faster, although not by much, as we don't have to resolve newest versions. We're essentially doing a frozen build.
[I've previously …
=> Use npm ci instead of npm install for CI pipeline

electron/execution.js, src/App.tsx, src/common/shared.ts, src/common/types.ts, src/components/ControlButton.tsx, src/components/ExportScriptButton.tsx, src/components/Header/HeaderControls.tsx, src/components/Header/StatusIndicator.tsx, src/components/Header/Title.tsx, src/components/StepsMonitor.tsx, src/components/TestButton.tsx, src/components/TestResult.tsx, src/contexts/TestContext.ts, src/hooks/useSyntheticsTest.ts
Resolves #106.
First step at implementing the latest recorder designs. This updates the header to match the styling, and migrates the buttons and functionality from elsewhere in the app to be in the header.
We can hold off on merging this until the follow-up PR adding the updated body is ready. My goal with this dedicated PR is to limit the scope and review burden.
=> feat: Implement updated header UI

jest.unit.setup.js, src/App.tsx, src/common/shared.test.ts, src/components/Header.tsx, src/components/Header/HeaderControls.test.tsx, src/components/Header/HeaderControls.tsx, src/contexts/StepsContext.ts, src/contexts/UrlContext.ts
Resolves #124.
The purpose of this PR is to prepare the recorder for release. The most notable reason, as noted in #124, is to unify the updated Play/Pause/Restart flow with the new header we recently merged.
We should also look for any glaring UX/export issues. The recorder is in a transitional UI state, but there is a lot of improved functionality we would like to release in the meantime until the UI re-vamp is complete.
Most notable is the move from the original start/end buttons to the header.
Try starting/pausing/stopping journey recording to make sure the recorder is working.
=> [Other] Prep for release

README.md
Currently the dev section of the project's README does not specify that the user check their `node` version before trying to `npm install`. This can set them up for unpleasant errors that they need to check the troubleshooting section below for.
In my opinion, it's reasonable to check this every time before attempting to do an install, so we should include a note at the start of the dev process that will ask the user to check that their current version is the one supported by the recorder. This can cut down on the number of bad experiences that people will have when they are attempting to run the recorder for the first time.
Check for typos and bad writing style.
Ensure that the command(s) specified in the change look correct.
=> chore: Update dev docs to recommend checking node version before `npm install`

src/App.tsx, src/common/shared.ts, src/components/AssertionDrawer.tsx, src/components/Header/Title.tsx, src/components/StepsMonitor.tsx, src/contexts/CommunicationContext.ts, src/hooks/useSyntheticsTest.ts
Resolves #142
Per the linked issue, we have numerous imports of `electron-better-ipc` via `window.require`, which works fine in production but makes the code excruciating to test. Rather than introduce strange testing patterns throughout the codebase, I propose we use this `CommunicationContext`, which uses `window.require` as a single point of entry for `ipc`. 
We can then share this reference throughout the application, and modify any functions that were performing a direct import to use dependency injection instead. This will allow us to supply mocks very easily for any component or helper function that previously performed the import internally.
Run the recorder, record some steps, view exported code, run test and see the results. All of these activities will ensure that the IPC is …
=> chore: Remove direct `ipc` imports, centralize import with `CommunicationContext`

package.json
Renames the app ID specified in the `package.json` to correspond to the ID we plan to use when notarizing the application for macOS.
=> chore: Rename app id to correspond to the ID planned for notarization use

.gitignore, demo-app/.gitignore, demo-app/.npmrc
Purpose here is to ignore a `package-lock.json` if it's created on the demo app during an install run.
Also, this added an empty line at the bottom of the `package.json`, I'm not sure if this will differ based on the dev platform.
Run `npm i` or `npm ci` and see if a `package-lock.json` shows up in the demo app directory.
=> Ignore `demo-app/package-lock.json`

.gitignore, package.json
Adds a `--watch` option for the npm test script with coverage flag set to aid with the unit test developer experience.
Run `npm run test:unit:watch` to start `jest` in watch mode. `--coverage` flag is also set to generate coverage report for checking code paths within functions.
No user impact.
=> chore: add watch script for unit test DX, ignore `coverage` dir

package-lock.json, package.json
We should endeavor to keep the recorder in sync with the latest version of Synthetics.
Simply bumps the depended version of Elastic Synthetics.
If CI passes there should be little else to investigate, but running the application on this branch as a quick smoke test is fine.
=> chore: Bump Synthetics to beta-19

.gitignore, package.json
> ⚠️ As requested by @shahzad31, I (@lucasfcosta) am now responsible for this PR, so I'll be the ones pushing commits and responding to comments in this issue.
This PR adds the ability to open Recorder directly from Kibana (or any other website) through a link using the `elastic-synthetics-recorder-protocol`.
You could, for example, use the following `EuiLink` to open the recorder:
```
<EuiLink href={`elastic-synthetics-recorder://`}>Open Script Recorder</EuiLink>
```
> Please notice that this PR/task does not include adding the relevant links in Kibana, and that that will be covered separately in https://github.com/elastic/kibana/issues/120638.
For now, there is no way to determine that the recorder is installed or not. Therefore, users which do not have the recorder installed will see …
=> Open Synthetics recorder directly from kibana via link

.prettierignore
Prettier was complaining about the `dist` folder after I had done a production build.
We should ignore the formatting of files in that directory.
N/A
Run `npm pack` and try to commit some files in a tracked location. The pre-commit hooks should fire, but they shouldn't block you from committing because of formatting errors within your `dist` folder.
=> chore: Ignore code formatting in `dist` dir

e2e/tests/runTest.test.ts, src/components/TestButton.tsx
Resolves #127.
Makes it so the user can't have the recorder run their script until they've finished recording.
We've decided that it's a better experience if the user doesn't attempt to run their test until after they terminate their recording session.
1. Run the recorder
2. Start a recording session
3. Observe that the replay steps button is disabled
4. Close your Chromium recording session
5. Observe that you can now replay the steps you recorded
=> feat: Disallow test run during recording session

electron/execution.js, electron/menu.js, src/common/shared.test.ts, src/common/shared.ts, src/common/types.ts, src/components/ActionStatusIndicator.tsx, src/components/Header/HeaderControls.tsx, src/components/TestResult/ResultBody.tsx, src/components/TestResult/ResultErrorBody.tsx, src/components/TestResult/styles.tsx, src/contexts/TestContext.ts, src/helpers/resultReducer.test.ts, src/helpers/resultReducer.ts, src/hooks/useSyntheticsTest.ts
part of #61 
When replaying the script, the test result is returned to the frontend after reaching the end of the journey(either success or fail). We'd like to see progressive feedback when each step is finished.
When the output is returned from the Synthetics CLI, Electron parses the output and constructs event object and then sends it via `webContents.send()`. The available event types are `journey/start`, `journey/end`, and `step/end` at the moment. The frontend subscribes to the event emitter and displays relevant result information whenever available. 
click the Replay Steps button to start the test, observe the application showing feedback after each step while the test is still executed in the browser.
=> feat: Asynchronously report journey test result

e2e/tests/testResult.test.ts, electron/execution.js, src/App.tsx, src/common/shared.test.ts, src/common/types.ts, src/components/TestResult/ResultBody.tsx, src/components/TestResult/ResultErrorBody.tsx, src/components/TestResult/ResultFlyoutItem.tsx, src/components/TestResult/ResultTitle.tsx, src/components/TestResult/styles.tsx, src/helpers/resultReducer.test.ts, src/hooks/useRecordingContext.ts, src/hooks/useSyntheticsTest.ts
Resolves #131.
As pictured below, shows all the actions in the result panels:
I have moved the duration value to the top of the step panel, because otherwise the duration element is appended to all of the actions and is misleading. Today, we only have resolution to the step level in terms of duration.
I am working on some [upstream changes](https://github.com/elastic/synthetics/pull/457) to Synthetics that should allow us to get action-level performance. At that point, we should be able to supply duration value for each item in this list, along with a cumulative duration value displayed in the heading.
Because we don't have action-level resolution, this means that all actions within a step currently show as the same status. If one action fails, all the actions in the step need to be …
=> feat: Show all action titles in step containers for test result flyout

package-lock.json, package.json, public/index.html, src/App.tsx, src/components/TestResult/ResultFlyoutItem.tsx, src/components/TestResult/ResultTitle.tsx, src/components/TestResult/styles.tsx, src/contexts/StyledComponentsEuiProvider.tsx
Resolves #167.
As noted in the linked issue, we aren't using the latest and greatest EUI theme. Fixing that here.
There may be minor things that break and are tough to notice. It might be worthwhile to build a binary from `main` and compare it against this branch in dev mode.
There should be no functional change with this patch, it should update EUI and utilize the Amsterdam styles.
=> fix: Update EUI version and switch to Amsterdam

.husky/pre-commit, demo-app/package.json, package-lock.json, package.json, src/App.tsx
The pre-commit hook aspect of the repo leaves a lot to be desired. I've added `lint-staged` which greatly improved the `lint:fix` functionality in terms of making commits to the repo.
Additionally, I've updated several dependencies that could use a bump, and installed missing peer dependencies to remove warning messages.
There should be no functional change to the recorder.
`lint-staged` should kick in when attempting to commit changes.
Ensure the recorder builds/runs ok. Passing CI should also be a positive indicator that this patch is alright.
Make a lint error such as removing one of the copyright headers from a source file, stage it and attempt to commit. The file should automatically be updated to include the header as part of the commit. Don't push test commits.
=> chore: update deps and add `lint-staged`

e2e/services/electron.ts, e2e/tests/assertionInfo.test.ts, src/common/shared.ts, src/components/ActionElement/ActionElement.tsx, src/components/Assertion/Assertion.tsx, src/components/Assertion/AssertionInfo.tsx
Resolves #65.
Adds a tooltip to the assertion element's heading per the designs.
Note: it does not include a link as the design indicates. I'm not sure what location that link should go to, and the tooltip's default behavior is to collapse when the mouse is no longer hover on the child element.
We can modify this implementation by fleshing out this requirement more.
Record steps, insert an assertion, edit it and see the tooltip appear over the icon.
=> feat: Add tooltip to assertion element heading

src/components/ActionElement/ActionElement.tsx
Resolves #162.
Assertions are expanded when created.
I've updated the inline state management for assertion elements to start out as expanded.
1. Record some actions
1. Add an assertion after one of your actions
1. Observe that the assertion you added is expanded when created
=> fix: Make assertions expanded on init

.eslintrc.js, e2e/tests/runTest.test.ts, src/components/ControlButton.tsx, src/components/Header/HeaderControls.test.tsx, src/components/Header/HeaderControls.tsx, src/components/TestButton.tsx
closes #163 
When the recorder's viewport width is smaller than a certain size, the buttons hide the label and only show the icon. This PR adds a tooltip to the buttons when the label is disappeared due to mentioned reason.
Although there are some things to be clarified before merging this PR:
- When the script is not recorded yet, the test button shows a tooltip with a descriptive message rather than a label (as it was before)
[![Image from Gyazo](https://i.gyazo.com/c732e9d5620a32d3971b13e7f8b8df06.gif)](https://gyazo.com/c732e9d5620a32d3971b13e7f8b8df06)
- When the script is recorded, the test button also shows a label
[![Image from Gyazo](https://i.gyazo.com/ef1a73d5bbab0b77b3178d2b2e1510db.gif)](https://gyazo.com/ef1a73d5bbab0b77b3178d2b2e1510db)
=> fix: Show label as tooltip when the viewport width is small

src/components/ControlButton.tsx
As part of #179 I merged a defect that caused a fill to be applied to all instances of `ControlButton`. This patch fixes it to restore the intended functionality.
Changes the `fill` prop to be conditional again.
Make sure that not all of the buttons have `fill`s.
=> fix: Fill defect for `ControlButton`

.ci/Jenkinsfile, .ci/Makefile
Automate the release and publishing steps.
* Tag based event (`v<major>.<minor>.*`)
* Notify if something bad happened
* Create draft release
* Skip all the stages but build and release when a tag release is created, every commit is validated in the CI either coming from a PR or merged to the main branch or release branches, therefore there is no need to validate it again when a tag is created from a validated commit.
* Package and upload the artifacts as assets to the GitHub release
* Sign the artifacts
* Confirm what slack/email to be used for notifications.
=> ci: release tag based (stage 1)

package-lock.json, package.json
+ The PW fork has been moved to `elastic` org from my personal repo, so changing that to reflect our package.json.
+ Some of the deps in `package-lock` for babel plugins were not updated as it was importing a older version.
=> fix: reference the correct pw fork

e2e/tests/navigation.test.ts, electron/execution.js, package-lock.json, package.json, src/App.tsx, src/common/shared.test.ts, src/common/shared.ts, src/common/types.ts, src/components/ActionDetail/ActionDetail.tsx, src/components/Assertion/Assertion.tsx, src/components/ExportScriptFlyout/Flyout.tsx, src/components/StepList/StepDetails.tsx, src/components/StepSeparator.tsx, src/contexts/StepsContext.ts, src/helpers/generator.test.ts, src/helpers/generator.ts, src/hooks/useStepsContext.test.ts, src/hooks/useStepsContext.ts, src/hooks/useSyntheticsTest.ts
Resolves #169.
Depends on https://github.com/elastic/synthetics/pull/457 + a new release of Synthetics.
This change goes alongside a patch to Synthetics.
This change would switch the `Steps` type from `Array<ActionInContext[]>` to `Array<{ actions: ActionInContext[]; name?: string}>`; This allows us to natively support custom fields at the step level, whereas today we're using nested `Array`s and have less flexibility when it comes to fixing state to the individual steps.
This change also would move the `Step` and `Steps` types to Synthetics to avoid circular references for some recorder-specific functionality I added that allows us to pass these objects cleanly to synthetics and preserve the steps the user will create/modify after they're done recording.
This branch relies on …
=> feat: switch `Steps` data structure from nested array to map

src/components/Header/HeaderControls.tsx, src/components/Header/UrlField.tsx
Resolves https://github.com/elastic/synthetics-recorder/issues/161.
Previously the URL input would not expand to fill available space. This PR makes the input maintain its original size, unless the user begins to enter an excessively long URL. In that case, the input field will expand to the bounds of the parent element.
Additionally, the `grow` prop for the recording controls is now dependent on the URL. It will `grow` for small URLs, but to maximize space usage it will stop `grow`ing so the URL field can fill the entirety of the available whitespace in the header controls area.
Check that a smaller URL value results in the field staying small.
Check that a larger URL results in the field filling the available space in the header control section.
=> fix: URL input expands for longer value

src/components/Header/HeaderControls.tsx
Resolves #203.
Make the `Test` button disabled during recording/paused states.
One-line change.
=> fix: Make Test button disabled during recording/paused states

src/components/Header/HeaderControls.tsx
Resolves #202.
Fixes header layout when Paused.
One-line change.
=> fix: Header layout when paused

e2e/tests/assertionInfo.test.ts, src/components/ActionElement/ActionElement.tsx
Resolves #201.
Conditionally renders the child for `ActionElement`, which will cause all local state to be destroyed when the element is closed.
The side effect of this change is that the default values for the edit forms will reset between close/open events.
Open an assertion and an action element, modify some values in the forms, then close and reopen the elements. Your ephemeral changes should be lost.
=> fix: Reset default values when action/assertion edit view closes

e2e/tests/actionValues.test.ts, src/components/ActionElement/HeadingText.tsx
fixes #210 
(possibly fixes #200)
It shows the correct URL in Action header after updating the url value
[![Image from Gyazo](https://i.gyazo.com/7f3be4677f83ef4f38f8df152deffa98.gif)](https://gyazo.com/7f3be4677f83ef4f38f8df152deffa98)
Use actionInContext.action.url instead of actionInContext.frameUrl
Update url in navigate action and notice that the url in action header is also updated to the correct value
Also the test will expect for the element header to contain the new value
=> fix: use action.url instead of frameUrl in header

src/components/Header/HeaderControls.tsx
Resolves #126.
Disables the start recording button if the URL field is empty.
1. Launch the recorder and try to start a journey without a URL.
1. Enter a URL and start recording a journey to ensure the original functionality remains intact.
=> fix: Disable record journey button when URL input is empty

src/App.tsx, src/components/SaveCodeButton.tsx, src/contexts/ToastContext.ts, src/hooks/useGlobalToasts.ts
Resolves #194.
When we save a file, now there will be a toast.
This PR adds a new context and hook associated with initializing the state used by the context. There's also a usage of the context in the `SaveCodeButton` component, so we can notify the user that their file was saved properly.
1. Record a journey
1. Use export flyout to expose the save button
1. Click the save button
1. The confirmation toast should appear
1. Make sure you can dismiss the toast, and that it goes away on its own
=> feat: Send toast on successful file save

src/components/TestResult/ResultFlyoutItem.tsx
Resolves #173.
Hides duration info for steps that never ran.
1. Record a journey with multiple steps
2. For any step except the last one, add an assertion you know will fail
3. Run a test
4. Observe that all skipped steps have no duration element displayed
=> feat: Hide duration element for skipped step

src/App.tsx, src/hooks/useRecordingContext.ts
Resolves #180.
Add a call to `setSteps([])` to clear the local step data just before we start a new recording session.
1. Record a journey.
2. Click "Start Over" button.
3. Observe that the old step data is gone.
=> fix: Clear steps as part of `startOver` procedure

src/components/StartOverWarningModal.tsx
Resolves #164.
Simply updates the copy in the "Start Over" warning modal.
Record a journey, then click "Start Over" and see the updated copy in the modal.
=> feat: Update start over warning modal copy

src/components/ActionElement/ActionElement.tsx, src/components/ActionElement/Behavior.tsx
Resolves #222.
Adds a status indicator to assertion elements as well as action elements.
1. Create an assertion.
1. See the status indicator.
Ensure the status color changes after a test run
=> feat: Add status indicator to assertion elements

electron/execution.ts
Fixes a defect we introduced recently as part of the backend transition from pure JS to TypeScript. I'm going to add tests for this function so we don't fail to notice things like this in the future.
We simply forgot to include an optional field in the response from the test procedure.
Run a journey that you expect to fail, and observe the code/data info in the test result flyout.
=> fix: Error not showing in failed test result flyout

src/common/shared.ts, src/components/ActionDetail/ActionDetail.tsx, src/components/Assertion/Assertion.tsx, src/helpers/generator.ts
Resolves #234.
When running a test, the title shown is not reflective of the other data associated with the action if the user has updated it.
I have modified the update logic to call the same `actionTitle()` function that we call when we initially create the action, so the same logic should apply to created and edited actions now.
1. Record a journey
1. Modify an action's data so as to update the title (e.g. create a new URL for a `navigate` action
1. Run the journey
1. In the test result flyout, observe that the title of your action reflects the updated value
=> fix: Refresh action title on update

electron/electron.ts, electron/menu.ts
Resolves #14.
Adds the ability to open a new window with the hotkey `CMD/CTRL+N`, intended for the macOS behavior where the application has 0 open windows but continues to run.
This UX differs from other platforms, but since it will only run when there are 0 windows open (and therefore the process should have already terminated), I didn't think we needed to add OS-specific checks.
The inspiration for this mirrors other electron applications like Slack or VS Code; when all of their windows are closed and the app is focused, `CMD+N` triggers a re-opening of the app with a fresh window.
This is WIP for the reasons explained below:
One way this could improve is to disable the menu option when there is `> 1 window` available. This might entail rebuilding the menu when certain handlers fire on …
=> feat: Add hotkey/menu item to open new window when 0 windows open on macOS

electron/execution.ts
Resolves #255.
Check the issue above for detailed repro steps - essentially if the user terminates the PW browser during a test run, the Recorder can't open the browser back up again ever.
We [recently introduced ](https://github.com/elastic/synthetics-recorder/pull/241/files#diff-33107fe7222398333570c06513ba085b86bd3564c21860f8a70886736dff81e6R91) an `isBrowserRunning` flag to prevent the recorder from launching unbounded browser instances.
Unfortunately, I failed to ensure that the flag would be reset in all cases. This change should correct that. It nests all setting of the `isBrowserRunning` flag inside of the pre-existing `try...catch...finally` blocks that the affected functions contain; whether the browser terminates manually or as planned, these flags should be reset afterwards. …
=> fix: Browser will not launch after manual termination of test run

electron-builder.yml, scripts/before-pack.js, scripts/download-chromium.js
Resolves #248.
Causes the `build`/`release` scripts to generate an Apple silicon binary in addition to the Intel one.
Simply updates the build config for the recorder.
You can do an `npm run pack` command to build fresh binaries locally. You should be able to run both the `x64` and the `arm64` versions without issues.
=> feat: Add option to build `arm64` binary

.ci/Jenkinsfile
Upload exe files to the google bucket so the release will consume those binaries
=> ci: upload exe files

package-lock.json, package.json
Bumps EUI to the latest version.
Aside from simply upgrading EUI, this version of the library eliminates some annoying erroneous error logging that has been plaguing the recorder for months.
Simply updates the EUI dependency, and its associated packages.
The only changes would be visual, and they are likely minute changes.
=> chore: Bump EUI to v58

electron-builder.yml
The latest builds have an app name "Elastic-Synthetics-Recorder". Before this, it was "Elastic Synthetics Recorder" (the current build has dashes between the words.)
In `electron-build.yml`, revert the `productName` field to have empty spaces instead of dashes. At the same time, in order to prevent any issue with empty space in artifacts name, we will use the `name` field from `package.json` instead of productName which does not contain empty space at all times. 
I'd love to check with @v1v about the change introduced [here](https://github.com/elastic/synthetics-recorder/pull/238/files#diff-abfd13c4441842dc2fc303311c40908ecd004ecec4c4bb5827c366b454a1f721L1) was due to the empty spaces in the productName having side effect when building artifacts. (If that was the only reason I've …
=> fix: remove dashes in app name

common/types.d.ts, electron/config.ts, electron/execution.ts, electron/syntheticsGenerator.ts, src/common/shared.test.ts, src/common/shared.ts, src/components/ExportScriptFlyout/Body.tsx, src/components/ExportScriptFlyout/Flyout.tsx, src/helpers/resultReducer.test.ts, src/hooks/useSyntheticsTest.ts
closes #254 
Aligning the usage of terminology within Synthetics product. We decided to use `Projects` instead of `Suites`.
Updated all the Suite usage both in code and visual contents so that we are not confused by deprecated terms in future development.
=> chore: rename `suites` to `projects`

electron/__snapshots__/syntheticsGenerator.test.ts.snap, electron/syntheticsGenerator.ts
Removes the comment that gets added before the navigation action is recorded. 
Record a journey that includes URL navigation. Make sure that your JS output will run properly.
=> fix: always wait for url when navigation is signaled

electron-builder.yml, electron/execution.ts, src/components/SaveCodeButton.tsx
- Resolves #276 
- Do not show _Script export successful_ toast when export is canceled
Use _filters_ option to specify js extension when saving the file with showSaveDialog.
Record a test, click Export button and omit `.js` extension from the file name and save the file. Check the file is saved as js file automatically.
demo on Windows:
https://user-images.githubusercontent.com/16660866/185129419-4f1f1923-5a42-4d30-b7a7-858a0974a6ca.mov
=> fix: Exports scripts as js file by setting filters for `dialog.showSaveDialog`

electron/__snapshots__/syntheticsGenerator.test.ts.snap, electron/syntheticsGenerator.ts
Do not include `url` options when generating `waitForNavigation` function as it often contains cachebuster query params and the following Test run fails with navigation time error as it doesn't match the exact URL due to the mentioned query params.
There were concerns about SPA not always yielding the navigation events, but this seems to be covered by:
1. [tests](https://github.com/microsoft/playwright/blob/main/tests/page/page-wait-for-navigation.spec.ts#L78) in Playwright showing `waitForNavigation` are supported for SPA
2. recorder doesn't seem to generate signal for SPA navigations which inturns never calls waitForNavigation  to be generated:
=> fix: drop url when generating waitForNavigation code

.prettierignore, README.md, src/components/ActionDetail/ActionDetail.test.tsx, src/components/ActionDetail/ActionDetail.tsx, src/components/Header/HeaderControls.test.tsx, src/helpers/test/render.tsx
fixes #282 
Allow editing `Value` field for the fill command.
Record a journey that types some text in an input element. 
Locate the `fill` action and go to Edit action. Check that the Value input field is editable and the change is applied when clicking the `Save` button.
=> fix: allow editing value when editing `fill` action

.ci/Jenkinsfile, .ci/scripts/release-ci.sh, assets/entitlements.mac.plist, electron-builder.yml, package-lock.json, package.json, scripts/before-pack.js, scripts/notarize.js
closes #51 
Notarize Mac applications so that the users can use the app without worrying about malicious code.
This PR introduces [electron-notarize](https://github.com/electron/electron-notarize) module to notarize the app and it is used when the Electron builder's `afterSign` hook is called. It is a recommended by electron-builder maintainers.
After the artefacts are released, download them, and run the following commands to verify the app has been notarized.
(Artifacts generated from this branch can be found [here](https://github.com/elastic/synthetics-recorder/releases/tag/untagged-053cedd0e62b7b3b9d3f))
- Validate the app is notarized(should see _source=**Notarized Developer ID**_):
```
❯ spctl -a -t exec -vv $PATH_TO_APP/Elastic Synthetics Recorder.app
$PATH_TO_APP//Elastic …
```
=> chore: notarize Mac applications

.ci/Jenkinsfile, .ci/scripts/docker-build.sh, .ci/scripts/run-test-in-docker.sh, .ci/scripts/run-test.sh, .gitignore, e2e/Dockerfile.jenkins
Revert partially https://github.com/elastic/synthetics-recorder/commit/5c91e170eded3f950443529bfdd7fe7f738100cc so it can mount the volume
There are some issues while using the docker build with a docker copy entry since the workspace is stored hence it can cause other issues related to what's the workspace used for testing.
By reverting https://github.com/elastic/synthetics-recorder/commit/5c91e170eded3f950443529bfdd7fe7f738100cc , restoring the workspace, setting the uid and using the node docker images things should be back to normal.
It runs successfully in the CI
or 
```bash
$ .ci/scripts/docker-build.sh
$ .ci/scripts/run-test-in-docker.sh
```
=> docker: use node docker images, mount volume and use node user

e2e/services/browser.ts, e2e/services/electron.ts
When running e2e tests, make sure the recording target browser is closed before closing electron instance so that each test can be finished. Currently, the second instance of electron starts and hangs forever when the browser is not closed.
(It seems to be an issue only to Mac)
Close all the contexts and browser before terminating electron. But the graceful termination of browser doesn't guarantee the complete close of the browser so adding setTimeout hack was needed
=> fix: close recording target browsers before terminating electron when testing

.ci/scripts/run-test-in-docker.sh, scripts/download-chromium.js, scripts/notarize.js
Recently updated `electron-notarize` module to recommended `@electron/notarize`, but forgot to update the module name where it's used.
Also fixed one of the functions that has been moved to a different path.
=> fix: import correct module for notarizing

.ci/Jenkinsfile, .github/workflows/ci.yml, .github/workflows/hello.yml, .github/workflows/test.yml
Use github actions for `Test` step to simplify the process and reduce the maintenance burden
We have had many issues with the testing environment in the past year, often caused by npm changing its behaviour or when using newer node versions (some contexts can be found [here](https://github.com/elastic/observability-robots/issues/1453) )
Having the permission issue #338 recently, and the possible fix #339 causing another issue affecting test results, I wanted to explore the github actions for running tests. I've tried to run the tests on macos(this let us bypass the setup for `Xvfb`) and It seems quite promising. Here's the impact I've found when opting in for github actions:
- Do not need to build the docker image and maintain it. The docker image is only used by the test step and when we …
=> test: try running tests on github action

src/helpers/test/defaults.ts, src/helpers/test/render.tsx
This is a preamble to https://github.com/elastic/synthetics-recorder/issues/264 as we are missing context helper defaults for the toast context. This will enable us to mock that context when testing components that dispatch notifications to the user.
Adds some defaults and supports overrides for testing components that call `ToastContext`.
There are no user-facing changes, if CI is passing this should be ok to merge. I have another patch lined up after this one that adds tests that make use of these defaults, so if there are any further issues they'll be resolved as part of that patch.
=> Add helper defaults for `IToastContext`

src/components/TestResult/TestResultFlyoutHeader.test.tsx, src/components/TestResult/TruncatedTitle.test.tsx
**NOTE TO REVIEWERS**: Do not review this until #353 is merged.
Related to #264.
Adds unit tests for `<TestResultFlyoutHeader />`.
Adds tests.
Review the test code. If it's passing CI and the code looks good, no further testing is required.
=> Add unit tests for `<TestResultFlyoutHeader />`

src/components/TestResult/ResultFlyoutItem.test.tsx
**NOTE TO REVIEWERS:** This should not be reviewed until #353 is merged.
Related to #264. Adds test for `<ResultFlyoutItem />`.
=> Add unit tests for `<ResultFlyoutItem />`

src/components/TestResult/TestResult.test.tsx, src/helpers/test/defaults.ts, src/helpers/test/render.tsx
**NOTE TO REVIEWERS:** This should not be reviewed until #353 is merged.
Related to #264. Adds test for `<TestResult />`.
=> Add unit tests for `<TestResult />`

src/hooks/useGlobalToasts.test.ts, src/hooks/useGlobalToasts.ts
**NOTE TO REVIEWERS:** This should not be reviewed until #353 is merged.
Related to #264. Adds test for `useGlobalToasts`.
=> Add unit tests for `useGlobalToasts`

electron/execution.ts
closes #277 
Enable chromium sandboxing for the recording target browser and synthetics
Pass flags enabling sandboxing
Run the [builds](https://github.com/elastic/synthetics-recorder/releases/tag/untagged-ae6f46a04338bfd80de4) of this branch on all supported OS:
=> chore: enable chromium sandboxing

src/helpers/test/ipc.ts, src/hooks/useRecordingContext.test.ts, src/hooks/useRecordingContext.ts
Related to #264. Adds test for `useRecordingContext`.
=> Add unit tests for `useRecordingContext`

src/helpers/test/render.tsx, src/hooks/useSyntheticsTest.test.tsx
Related to #264. Adds test for `useSyntheticsTest`.
=> Add unit tests for `useSyntheticsTest`

src/hooks/useTestResult.test.tsx
Related to #264. Adds test for `useTestResult`.
=> Add unit tests for `useTestResult`

electron/electron.ts, electron/menu.ts, scripts/notarize.js
closes #265 
Users can check license & thirdparty notices within the app from the Help > Acknowledgement menu item.
[![Image from Gyazo](https://i.gyazo.com/b62d3292db1abea603ee49d3589ca0a4.gif)](https://gyazo.com/b62d3292db1abea603ee49d3589ca0a4)
Get NOTICE.txt and display it in a child browser window. The path to do it is to click through _Help > Acknowledgement_.
The [initial plan](https://github.com/elastic/synthetics-recorder/issues/265#issuecomment-1219654515) was to add a button in About box that opens up the child window but Electron doesn't provide API or options to customize the About panel. So I chose to add it as a menu item to `Help` menu(Also notice that I've added _Learn more_ menu that links to the documentation page.)
=> feat: add acknowledgement menu item to show NOTICE.txt in app

jest.unit.config.js
Right now, we collect test coverage data on test files themselves.
This makes the coverage metrics in aggregate look much lower than they really are, as test files oftentimes contain more code than the files they're actually testing.
To test this, run `npm run test:unit:watch`. After the test runs complete, open the HTML doc at the root of the `coverage` directory and ensure that you don't see test files reflected in the coverage metrics.
=> Do not collect test coverage data on test files

src/helpers/test/defaults.ts, src/helpers/test/render.tsx, src/hooks/useDrop.test.tsx, src/hooks/useDrop.ts
Related to #264. Adds test for `useDrop`.
=> Add more unit tests for `useDrop`

src/components/StepSeparator/SeparatorActions.test.tsx, src/components/StepSeparator/SeparatorActions.tsx
Related to #264. Adds test for `SeparatorAction`.
=> Add unit tests for `SeparatorActions`

src/components/ActionDetail/ActionDetail.test.tsx, src/components/ActionDetail/FormControl.test.tsx, src/components/ActionElement/ActionElement.test.tsx, src/components/ActionElement/ActionElement.tsx, src/components/Header/HeaderControls.test.tsx, src/components/Header/UrlField.test.tsx, src/components/SaveCodeButton.test.tsx, src/components/TestResult/ResultTitle.test.tsx, src/components/TestResult/TestResult.test.tsx, src/components/TestResult/TruncatedTitle.test.tsx
Related to #264. Adds test for `ActionElement`.
=> Add unit tests for `ActionElement`

src/components/StepSeparator/EditStepNameInput.test.tsx
Related to #264. Adds test for `EditStepNameInput`.
=> Add unit tests for `EditStepNameInput`

src/components/ExportScriptFlyout/Body.test.tsx, src/components/ExportScriptFlyout/Body.tsx, src/components/ExportScriptFlyout/Flyout.test.tsx
Related to #264. Adds test for `ExportFlyout`.
=> Add unit tests for `ExportFlyout`

electron/electron.ts, electron/menu.ts
closes #363 
Review menu items 
- Shows relevant menu per platform(example: show app menu only for MacOS)
- Removes [confusing](https://github.com/elastic/synthetics-recorder/issues/14#issuecomment-1410188463) `New Main Window` from menu (but keep the shortcut) 
Run the build on each platform and check the menus:
- MacOS:
- Windows
- Linux
=> chore: remove new window from menu but keep the hotkey

package-lock.json, package.json, src/components/Header/HeaderControls.tsx, src/components/Header/Title.tsx
Upgrades EUI version to v76.
There should be minute or no GUI changes, and the app should pass all CI tests.
For this particular screen, the header remains un-dimmed, whereas in previous versions of EUI it was dimmed. I've conferred with the EUI team about this and they have told me it's working as designed and although it's different from how it looked before it isn't violating any of their design principles.
=> Upgrade EUI

src/components/Header/Title.tsx
closes [#182](https://github.com/elastic/synthetics-dev/issues/182)
Remove `Beta` batch from the header 🎉 
Confirm that `Beta` badge is not visible when launching the app
=> chore: remove beta badge :tada:

.github/workflows/opentelemetry.yml
Help to monitor the GitHub actions when they are executed using the OpenTelemetry data.
=> action: export GitHub workflow runs to OpenTelemetry traces

package.json
This doesn't resolve an open issue or do anything particularly required, but it seems a DX improvement in my opinion. We can close if others disagree.
Essentially, it runs `eslint` in `DEBUG` mode, which is apparently the [prescribed](https://github.com/eslint/eslint/issues/2152#issuecomment-86975010) method of achieving this. It would be cleaner if the package supported a `--list-files`-type of flag.
Runs `eslint` in debug mode to list the files linted, rather than an empty output like what it does today.
IMO this reinforces for the person running the script that everything is working ok, and it is easy to `npm run lint | grep {FILENAME}` if needed.
Run `npm run lint` and `npm run lint:fix`.
=> [Synthetics] Run lint in debug mode to list all files tested in stdout

package-lock.json, package.json
Updates `EUI` and `styled-components` to use more recent versions.
There should be no noticeable delta in terms of features or use.
Run the recorder and ensure that while smoke testing nothing seems off. If e2e tests are passing and everything looks visually ok, this is safe to merge.
=> [Chore] Bump EUI and styled-components

src/components/Header/HeaderControls.tsx, src/components/Header/Title.tsx
Resolves #396 .
Makes the recorder's page header static at the top of the viewport during scrolling, and removes its box shadow.
When we upgraded EUI we encountered some less-than-desired behavior (shown in the linked issue) where an expanded flyout leaves the title section of the page undimmed while the flyout is expanded. The true intention of this functionality is that the flyout will appear below a static heading UI, whereas ours fills in all the way to the top of the viewport.
To resolve this unwanted behavior, I've modified the page heading to be sticky, per the design standards shown in both the EUI docs and in multiple parts of Kibana. Now, when the user scrolls, the page heading will remain at the top of the viewport, and will remain accented when the flyout opens.
A side effect …
=> [UI] Make page title sticky and remove box shadow

docs/DOWNLOAD.md
For the 1.0.0 release we have a few arch options listed in the Downloads page that we don't support *yet*.
Removes a few arch options that we don't support.
Review the copy and check the links are working.
=> [Chore] Update downloads page arch

README.md, electron/api/runJourney.ts, package-lock.json, package.json
Upgrades Playwright to `v1.37.0` and Synthetics to `v1.4.0` in preparation for `v1.2.0` of the Recorder.
I updated the args we pass Synthetics, as it now supports a `--no-headless` flag.
I also updated the `README.md` a bit to reflect some common issues with the release process.
Build and run the recorder, test its features, it should work consistently with previous releases.
=> [Release] Upgrade Playwright to `v1.37.0` and Synthetics to `v1.4.0`

package-lock.json, package.json
I am no longer capable of pushing directly to upstream `main`, so making this PR to merge the change that contains the update. I think this is ok, since the release tag is what we should go off of for the release.
=> Merge v1.3.0 to main

.github/workflows/test-docs.yml
```cucumber
Given the Test workflow (.github/workflows/test.yml) with paths-ignore
When the GitHub check status called `test` is enabled as one of the rules in the Branch protection
Then it's required to synthetically set the GitHub check status called `test` for those changes that are in the `paths-ignore'
```
A new GitHub workflow that overrides the name of the GitHub check and listening for the files that have been [ignored in the test GitHub](https://github.com/elastic/synthetics-recorder/blob/a6f4b6cb915d94a74a06247e379c8a141f32af34/.github/workflows/test.yml#L6-L10) workflow.
Once it's merged
Unblocks https://github.com/elastic/synthetics-recorder/pull/482
=> chore(github-action): create test check status for docs only

RELEASE.md, docs/DOWNLOAD.md
Updates to the Release and Downloads docs in anticipation of the upcoming v1.3.0 release.
Provides some testing guidance for the basic quality gate process we have in place before we publish a release.
Also updates the Downloads page to work with the new release.
This should not be merged until the release is published.
Check for grammatical errors and make sure the instructions are clear.
=> [Chore] Update release docs

.buildkite/scripts/create-github-release.sh
Avoid interactive gh release, according to https://github.com/cli/cli/blob/5402e207ee89f2f3dc52779c3edde632485074cd/pkg/cmd/release/create/create.go#L113-L114
```bash
BUILDKITE_TAG=1.2.3 gh release \
create \
"${BUILDKITE_TAG}" \
--draft \
--generate-notes \
--repo v1v/synthetics-recorder 
https://github.com/v1v/synthetics-recorder/releases/tag/untagged-f847e66934fea83d4b33
```
=> ci(release): avoid interactive approach

package-lock.json, package.json
Simply bumps package version because we did not do this in a previous PR.
=> Bump Recorder patch version to 1.4.14
