elastic/synthetics-recorder

src/common/shared.test.ts
src/common/shared.ts
src/components/AssertionDrawer.tsx
src/contexts/AssertionContext.ts
src/hooks/useAssertionDrawer.ts

Resolves https://github.com/elastic/synthetics-recorder/issues/20.
~This is WIP -~ adding additional assertion commands. Waiting for agent-side updates to synthetics before building this out further.

feat: add more assertion commands

---

src/common/shared.test.ts
src/common/shared.ts

As a part of #29 I merged new assertion commands, but I added a commit after the repo became public and I had to re-create my fork. As a result, some minor revisions failed to make it in. This PR merges in the missing commits.

feat: add more assertion commands pt. 2

---

electron/execution.js
src/App.tsx
src/common/types.ts
src/components/Header.test.tsx
src/components/Header.tsx
src/components/StartOverWarningModal.tsx
src/components/StepList/StepDetails.tsx
src/components/Steps.tsx
src/contexts/RecordingContext.ts

**NOTE TO REVIEWERS:** Depends on https://github.com/elastic/synthetics-recorder/pull/114.
Resolves #96.
This is a reposting of https://github.com/elastic/synthetics-recorder/pull/97; after we brought this repo public my fork lost association with open PRs and new commits would not show up/trigger the CI process.
After numerous attempts to re-establish the connection I opted to simply re-open a new PR. Description and previous comments available at the link above.

feat: 96/abort session and clear steps

---

package-lock.json
package.json

Updates a number of project dependencies.
This updates a number of our project dependencies to new versions. Most importantly, EUI is bumped to its latest major version, which has official support for the version of React we're using.
These changes should be relatively transparent. If all tests are passing and a cursory smoke test of the various user flows appears to work there should be no further cause for concern.

chore: Bump deps

---

README.md
e2e/tests/actionValues.test.ts

Resolves https://github.com/elastic/synthetics-recorder/issues/196.
Adds an update to the project's README that explains an error that can happen now that users are allowed to define and arrange their own step separators.
Just a docs update.
Have a look at the example code and make sure it all makes sense. This code came directly from a real journey I ran, so it should be alright, but weirdness can happen.
Also find any typos, help eliminate passive voice, etc.

chore: Add update to `README.md` to explain undefined reference error

---

package-lock.json
package.json

Upgrades EUI v52 to v55.
No material code changes.
Look for UI-related defects.

chore: Bump EUI version

---

src/helpers/generator.test.ts
src/helpers/test/createAction.ts

Resolves #193.
Adds some new unit test creator functions that accept override objects to specify custom field values.
Reduces the complexity of the generator tests by a bit. Can probably be further reduced.
Unit tests should all continue passing.

chore: Simplify generator unit test

---

.ci/Jenkinsfile
.ci/scripts/acs-signing.bat
.ci/scripts/create-github-release.sh

Sign windows binaries
https://github.com/v1v/synthetics-recorder/releases/tag/untagged-f5a09d0327a2708aba7c
The exe file doesn't cause warning messages on a Windows VM.

chore: Automatic exe signing and release 

---

electron/electron.ts
package-lock.json
package.json

Brings electron to up-to-date version. It also mitigates one of the security vulnerability issues.

chore: update electron version

---

.github/dependabot.yml

This will align the behavior here with synthetics https://github.com/elastic/synthetics/blob/main/.github/dependabot.yml

Create dependabot yml for package updates, similar to synthetics

---

electron/__snapshots__/syntheticsGenerator.test.ts.snap
package-lock.json
package.json

Update deps
- @elastic/synthetics@beta.38
- playwright@[1.27.1](https://github.com/elastic/playwright/tree/1.27.1-recorder)

chore: update synthetics agent and playwright

---

.github/workflows/hello.yml

Add initial workflow to enable GH Actions workflows.

Add initial workflow

---

package-lock.json
package.json

Updates undici.
Should be a transparent dep bump.
Make sure recorder works and all CI processes are green.

Upgrade undici

---

README.md

I'm updating Elastic's playwright fork and modifying some of the instructions based on that experience.
Just check for spelling, grammar, etc., and make sure new instructions make sense.
No need to validate per se as it's based on my own experience following the instructions. As long as everything I'm adding seems to make sense, no need to validate that the instructions are working.

[Chore] Update README playwright instructions

---

README.md
electron/__snapshots__/syntheticsGenerator.test.ts.snap
electron/syntheticsGenerator.ts

- Bring codegen up-to-date as [Playwright](https://github.com/elastic/playwright/blob/1.31.1-recorder/packages/playwright-core/src/server/recorder/javascript.ts#L28)
-  Add updating codegen section in README.md 
Resolves https://github.com/elastic/synthetics-recorder/issues/393.

chore: bring codegen up-to-date

---

docs/DOWNLOAD.md

Adds live download links for mac arm/mac x64/linux/windows to the downloads page.
Adds links. You can click them and they should cause artifacts to download.
Click the links.

[Docs] Add S3 links to `DOWNLOAD.md`

---

docs/DOWNLOAD.md

Updates the `DOWNLOAD.md` file to link to the latest binaries for v1.1.0.
Updates links.
Check that links work.

Update `DOWNLOAD` file for `1.1.0`

---

docs/DOWNLOAD.md

Updates the `DOWNLOADS.md` file to include links for the latest versions of the recorder binaries.
**NOTE:** I also modified the formatting to use proper HTML headings instead of relying on bolded text for segmentation of the document.
N/A, just changing over the version.
Test the download links and ensure they all work. No further testing should be needed, the binaries themselves are tested separately.

Updated `DOWNLOAD.md` for version 1.2.0

---

NOTICE.txt
package-lock.json
package.json
src/components/StepSeparator/index.tsx

Bumps dependencies in preparation for bumping Synthetics and releasing v1.3.0 of the recorder.

V1.3.0 upgrade prep

---

RELEASE.md
package-lock.json

+ Fix the pack command when running releases - https://github.com/elastic/playwright/commit/dd42db10cf131355b4c879e7fd7ac556bddac660

fix: export browserFetcher correctly for playwright-core

---

catalog-info.yaml

Change the pipeline name related to the Release itself

ci(buildkite): rename pipeline

---

.buildkite/scripts/create-github-release.sh

fix: release artifacts creation

---

package-lock.json
package.json

Update Synthetics library to 1.18.0, same underlying playwright version.

Update Synthetics to 1.18.0

---

docs/DOWNLOAD.md

Upgrades docs file to point users to latest release.
N/A
Test the links and ensure they download the appropriate versions of the recorder.

docs: Update DOWNLOAD.md to point to latest release
